- name: functions
  hosts: local
  connection: local
  vars:
    technologies: Devops, mysql, python, Ansible  #string
    tags:
      Application: payment
      Environment: prod
    # List  
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: Dev
  tasks:
  - name: convert string into list
    ansible.builtin.debug:
      msg: "technologies are:  {{ technologies | split (',') }}"


  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are {{ tags | dict2items }}"
  
  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"


  - name: read yaml and take into variables
    ansible.builtin.set_facts:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: convert yam into json
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json }}"

  - name: save json to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"