- name: prompt level variables
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: What is your name?
    private: false
  - name: password
    prompt: What is your password?
    private: true
  tasks:
  - name: Print credentials
    ansible.builtin.debug:
      msg: "Hello, username: {{ username }}, Password: {{ password }}"